### ISSUE TITLE
Plugin creates exception when connection interrupted

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#32]
This could probably be handled more gracefully.

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2019-02-02 21:01:18 +0100 (Sat, 02 Feb 2019)
Build-Date:2019-02-04 21:50:11
Revision:14760
Relative:URL: ^/trunk

Identification: JOSM/1.5 (14760 en) Linux Ubuntu 18.04.2 LTS
Memory Usage: 235 MB / 1820 MB (67 MB allocated, but free)
Java version: 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12, Oracle Corporation, OpenJDK 64-Bit Server VM
Screen: :0.0 1366x768
Maximum Screen Size: 1366x768
Java package: openjdk-8-jre:amd64-8u191-b12-2ubuntu0.18.04.1
WebStart package: icedtea-netx:amd64-1.6.2-3.1ubuntu3
Java ATK Wrapper package: libatk-wrapper-java:all-0.33.3-20ubuntu0.1
VM arguments: [-Dicedtea-web.bin.name=javaws, -Dicedtea-web.bin.location=/usr/bin/javaws, -Djava.security.manager, -Djava.security.policy=/etc/icedtea-web/javaws.policy]

Plugins:
+ ImproveOsm (157)
+ OpenStreetCam (184)
+ pbf (34867)
+ tageditor (34560)
+ todo (30306)
+ turnlanes-tagging (272)
+ turnrestrictions (34867)

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1

Last errors/warnings:
- W: No configuration settings found.  Using hardcoded default values for all pools.
- W: Region [TMS_BLOCK_v2] Resetting cache
- W: java.net.UnknownHostException: api.openstreetmap.org
- E: java.net.UnknownHostException: api.openstreetmap.org
- E: org.openstreetmap.josm.io.OsmTransferException: Could not connect to the OSM server. Please check your internet connection.. Cause: java.net.UnknownHostException: api.openstreetmap.org
- W: java.net.UnknownHostException: api.openstreetmap.org
- W: Already here java.net.UnknownHostException: api.openstreetmap.org
- E: java.net.UnknownHostException: api.openstreetmap.org
- W: org.openstreetmap.josm.io.OsmTransferException: Could not connect to the OSM server. Please check your internet connection.. Cause: java.net.UnknownHostException: api.openstreetmap.org
- E: Handled by bug report queue: java.lang.ExceptionInInitializerError. Cause: java.lang.NullPointerException


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: pool-1-thread-1 (52)
java.lang.ExceptionInInitializerError
	at org.openstreetmap.josm.plugins.openstreetcam.OpenStreetCamPlugin.lambda$new$0(OpenStreetCamPlugin.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.openstreetcam.handler.SearchServiceHandler.handleException(SearchServiceHandler.java:215)
	at org.openstreetmap.josm.plugins.openstreetcam.handler.ServiceHandler.listSigns(ServiceHandler.java:342)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.filter.DetectionTypeContent.<init>(DetectionTypeContent.java:26)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.filter.DetectionTypeContent.<clinit>(DetectionTypeContent.java:22)
	... 4 more
}}}
```

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue, the fix will be available in the next release.
