### ISSUE TITLE
Nearby photos throws NPE

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#33]
Clicking on nearby photo icon in photo panel
```
2019-03-26 15:16:19.599 SEVERE: Handled by bug report queue: java.lang.NullPointerException
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.openstreetcam.util.Util.nearbyPhotos(Util.java:128)
	at org.openstreetmap.josm.plugins.openstreetcam.DataSet.nearbyPhoto(DataSet.java:396)
	at org.openstreetmap.josm.plugins.openstreetcam.handler.SelectionHandler.selectNearbyPhoto(SelectionHandler.java:260)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.photo.ButtonPanel.notifyNearbyPhotoObserver(ButtonPanel.java:316)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.photo.ButtonPanel$ClosestPhotoAction.actionPerformed(ButtonPanel.java:420)
```

**Comment by beataj-telenav** [comment]
Thanks for reporting the issue. What is the version of your OSC plugin?

**Comment by beataj-telenav** [comment]
Fixed in build 236.
