### ISSUE TITLE
Double clicking on detection in aggregated detections panel causes exception

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/josm-plugin#36]
I have the aggregated detections panel open like this:

<img width="596" alt="Screenshot 2019-04-22 16 15 31" src="https://user-images.githubusercontent.com/120452/56535835-e1e54e80-6519-11e9-8f13-e8f874bf5ff7.png">

When I double-click on a row in the detections list, a photo panel opens ('capturing' the second click, I think) and I get an exception:

```
{{{
URL:https://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2019-03-31 21:17:00 +0200 (Sun, 31 Mar 2019)
Build-Date:2019-03-31 20:25:18
Revision:14945
Relative:URL: ^/trunk

Identification: JOSM/1.5 (14945 en) Mac OS X 10.14.4
OS Build number: Mac OS X 10.14.4 (18E226)
Memory Usage: 1082 MB / 1820 MB (617 MB allocated, but free)
Java version: 1.8.0_201-b09, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Screen: Display 188956751 1920x1080, Display 69733446 1680x1050
Maximum Screen Size: 1920x1080
VM arguments: [-Djava.library.path=/Applications/JOSM.app/Contents/MacOS, -DLibraryDirectory=${HOME}/Library, -DDocumentsDirectory=${HOME}/Documents, -DApplicationSupportDirectory=${HOME}/Library/Application Support, -DCachesDirectory=${HOME}/Library/Caches, -DApplicationDirectory=${HOME}/Applications, -DAutosavedInformationDirectory=${HOME}/Library/Autosave Information, -DDesktopDirectory=${HOME}/Desktop, -DDownloadsDirectory=${HOME}/Downloads, -DMoviesDirectory=${HOME}/Movies, -DMusicDirectory=${HOME}/Music, -DPicturesDirectory=${HOME}/Pictures, -DSharedPublicDirectory=${HOME}/Public, -DSystemLibraryDirectory=/Library, -DSystemApplicationSupportDirectory=/Library/Application Support, -DSystemCachesDirectory=/Library/Caches, -DSystemApplicationDirectory=/Applications, -DSystemUserDirectory=/Users, -DUserHome=${HOME}, -DSandboxEnabled=true, -DLaunchModifierFlags=0, -DLaunchModifierFlagCapsLock=false, -DLaunchModifierFlagShift=false, -DLaunchModifierFlagControl=false, -DLaunchModifierFlagOption=false, -DLaunchModifierFlagCommand=false, -DLaunchModifierFlagNumericPad=false, -DLaunchModifierFlagHelp=false, -DLaunchModifierFlagFunction=false, -Dapple.laf.useScreenMenuBar=true, -Dcom.apple.macos.use-file-dialog-packages=true, -Dcom.apple.macos.useScreenMenuBar=true, -Dcom.apple.mrj.application.apple.menu.about.name=JOSM, -Dcom.apple.smallTabs=true]
Dataset consistency test: No problems found

Plugins:
+ ImproveOsm (167)
+ Mapillary (1.5.18)
+ MicrosoftStreetside (34977)
+ OpenStreetCam (230)
+ apache-commons (34908)
+ apache-http (34908)
+ auto_tools (73)
+ ejml (34908)
+ geojson (124)
+ geotools (34908)
+ javafx-osx
+ jaxb (34908)
+ jna (34908)
+ jts (34908)
+ opendata (34911)
+ photo_geotagging (34908)
+ reltoolbox (34977)
+ reverter (34953)
+ tageditor (34977)
+ todo (30306)
+ turnlanes (${version.entry.commit.revision})
+ turnlanes-tagging (281)
+ turnrestrictions (34977)
+ utilsplugin2 (34977)

Map paint styles:
+ https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Coloured_buildings&zip=1

Last errors/warnings:
- E: java.io.IOException: java.util.concurrent.ExecutionException: [security, find-certificate, -c, Government Root Certification Authority, -p, /System/Library/Keychains/SystemRootCertificates.keychain]. Cause: java.util.concurrent.ExecutionException: [security, find-certificate, -c, Government Root Certification Authority, -p, /System/Library/Keychains/SystemRootCertificates.keychain]
- W: Plugin javafx-osx requires Java version 10. The current Java version is 8. You have to update Java in order to use this plugin.
- E: unable to find dependency javafx for plugin MicrosoftStreetside
- W: No configuration settings found.  Using hardcoded default values for all pools.
- E: Handled by bug report queue: java.lang.NullPointerException
- E: Handled by bug report queue: java.lang.NullPointerException


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (19) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.photo.PhotoPanel.getPointOnImage(PhotoPanel.java:260)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.photo.PhotoPanel.access$400(PhotoPanel.java:48)
	at org.openstreetmap.josm.plugins.openstreetcam.gui.details.photo.PhotoPanel$MousePressedAdapter.mouseClicked(PhotoPanel.java:393)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by beataj-telenav** [comment]
The issue will be fixed in the next release, thanks for reporting it.

**Comment by beataj-telenav** [comment]
Fixed in build 236.
